<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gm</string>
	</array>
	<key>name</key>
	<string>GameMonkey</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.gamemonkey</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.constant.gamemonkey</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.gamemonkey</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match stuff like: Sound.prototype = { … } when extending an object</string>
			<key>match</key>
			<string>([a-zA-Z_?.$][\w?.$]*)\.(prototype)\s*(=)\s*</string>
			<key>name</key>
			<string>meta.class.gamemonkey</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.gamemonkey</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.constant.gamemonkey</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.gamemonkey</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.gamemonkey</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.gamemonkey</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.gamemonkey</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.gamemonkey</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.gamemonkey</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match stuff like: Sound.prototype.play = function() { … }</string>
			<key>match</key>
			<string>([a-zA-Z_?.$][\w?.$]*)\.(prototype)\.([a-zA-Z_?.$][\w?.$]*)\s*(=)\s*(function)?\s*(\()(.*?)(\))</string>
			<key>name</key>
			<string>meta.function.prototype.gamemonkey</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.gamemonkey</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.constant.gamemonkey</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.gamemonkey</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.gamemonkey</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match stuff like: Sound.prototype.play = myfunc</string>
			<key>match</key>
			<string>([a-zA-Z_?.$][\w?.$]*)\.(prototype)\.([a-zA-Z_?.$][\w?.$]*)\s*(=)\s*</string>
			<key>name</key>
			<string>meta.function.gamemonkey</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.gamemonkey</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.gamemonkey</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.gamemonkey</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.gamemonkey</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.gamemonkey</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.gamemonkey</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.gamemonkey</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match stuff like: Sound.play = function() { … }</string>
			<key>match</key>
			<string>([a-zA-Z_?.$][\w?.$]*)\.([a-zA-Z_?.$][\w?.$]*)\s*(=)\s*(function)\s*(\()(.*?)(\))</string>
			<key>name</key>
			<string>meta.function.gamemonkey</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.gamemonkey</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.gamemonkey</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.gamemonkey</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.gamemonkey</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.gamemonkey</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.gamemonkey</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match stuff like: play = function() { … }</string>
			<key>match</key>
			<string>([a-zA-Z_?$][\w?$]*)\s*(=)\s*(function)\s*(\()(.*?)(\))</string>
			<key>name</key>
			<string>meta.function.gamemonkey</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.gamemonkey</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.gamemonkey</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.gamemonkey</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.gamemonkey</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.gamemonkey</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match regular function like: function myFunc(arg) { … }</string>
			<key>match</key>
			<string>\b(function)\s+([a-zA-Z_$]\w*)?\s*(\()(.*?)(\))</string>
			<key>name</key>
			<string>meta.function.gamemonkey</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.gamemonkey</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.gamemonkey</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.gamemonkey</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.gamemonkey</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.gamemonkey</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match stuff like: foobar: function() { … }</string>
			<key>match</key>
			<string>\b([a-zA-Z_?.$][\w?.$]*)\s*:\s*\b(function)?\s*(\()(.*?)(\))</string>
			<key>name</key>
			<string>meta.function.json.gamemonkey</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.gamemonkey</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.gamemonkey</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.gamemonkey</string>
				</dict>
				<key>12</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.gamemonkey</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.gamemonkey</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.gamemonkey</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.gamemonkey</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.gamemonkey</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.gamemonkey</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.gamemonkey</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.gamemonkey</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.gamemonkey</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Attempt to match "foo": function</string>
			<key>match</key>
			<string>(?:((')([^']*)('))|((")([^"]*)(")))\s*:\s*\b(function)?\s*(\()([^)]*)(\))</string>
			<key>name</key>
			<string>meta.function.json.gamemonkey</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.new.gamemonkey</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.instance.gamemonkey</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(new)\s+(\w+(?:\.\w*)?)</string>
			<key>name</key>
			<string>meta.class.instance.constructor</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
			<key>name</key>
			<string>constant.numeric.gamemonkey</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.gamemonkey</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.gamemonkey</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.gamemonkey</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.gamemonkey</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.gamemonkey</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.gamemonkey</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.gamemonkey</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.gamemonkey</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*\*(?!/)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.gamemonkey</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.documentation.gamemonkey</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.gamemonkey</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.gamemonkey</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.gamemonkey</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.gamemonkey</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(local|member|global|table|function)\b</string>
			<key>name</key>
			<string>storage.type.gamemonkey</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(break|continue|dowhile|else|for|foreach|goto|if|return|while)\b</string>
			<key>name</key>
			<string>keyword.control.gamemonkey</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|in)\b</string>
			<key>name</key>
			<string>keyword.operator.gamemonkey</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\btrue\b</string>
			<key>name</key>
			<string>constant.language.boolean.true.gamemonkey</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bfalse\b</string>
			<key>name</key>
			<string>constant.language.boolean.false.gamemonkey</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bnull\b</string>
			<key>name</key>
			<string>constant.language.null.gamemonkey</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bthis\b</string>
			<key>name</key>
			<string>variable.language.gamemonkey</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b()\b</string>
			<key>name</key>
			<string>support.class.gamemonkey</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(debug|typeId|typeName|typeRegisterOperator|typeRegisterVariable|sysCollectGarbage|sysGetMemoryUsage|sysSetDesiredMemoryUsageHard|sysSetDesiredMemoryUsageSoft|sysSetDesiredMemoryUsageAuto|sysGetDesiredMemoryUsageHard|sysGetDesiredMemoryUsageSoft|sysTime|doString|globals|threadTime|threadId|threadAllIds|threadKill|threadKillAll|thread|yield|exit|assert|sleep|signal|block|stateSet|stateSetOnThread|stateGet|stateGetLast|stateSetExitFunction|tableCount|tableDuplicate|print|format)\b(?=\()</string>
			<key>name</key>
			<string>support.function.gamemonkey</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|\-|\*|/|%|&lt;&lt;|&gt;&gt;|&amp;|\||\^|=|\+=|\-=|\*=|/=|%=|\?=|&amp;=|\|=|\^=|&lt;&lt;=|&gt;&gt;=|==|!=|&lt;=|&gt;=|&lt;|&gt;|!|\?|!\?|&amp;&amp;|\|\||\b(and|or|in)\b</string>
			<key>name</key>
			<string>keyword.operator.gamemonkey</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=[=(:]|^|return|&amp;&amp;|\|\||!)\s*(/)(?![/*+{}?])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.gamemonkey</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(/)[igm]*</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.gamemonkey</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.regexp.gamemonkey</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.gamemonkey</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\;</string>
			<key>name</key>
			<string>punctuation.terminator.statement.gamemonkey</string>
		</dict>
		<dict>
			<key>match</key>
			<string>,[ |\t]*</string>
			<key>name</key>
			<string>meta.delimiter.object.comma.gamemonkey</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.</string>
			<key>name</key>
			<string>meta.delimiter.method.period.gamemonkey</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{|\}</string>
			<key>name</key>
			<string>meta.brace.curly.gamemonkey</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)</string>
			<key>name</key>
			<string>meta.brace.round.gamemonkey</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[|\]</string>
			<key>name</key>
			<string>meta.brace.square.gamemonkey</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.gamemonkey</string>
	<key>uuid</key>
	<string>9ad610b8-c912-445b-bf8c-d7bf799b3d8e</string>
</dict>
</plist>
